#!/bin/bash
set -e

cd build32

PKG_CONFIG_PATH=/opt/lsb/lib/pkgconfig:/usr/lib/pkgconfig cmake .. -DFLAT_INSTALL=ON -DCMAKE_TOOLCHAIN_FILE=../cmake/lsb-4-0.cmake -DCMAKE_C_FLAGS="--lsb-besteffort" -DCMAKE_CXX_FLAGS="--lsb-besteffort" -DMPCDEC_INCLUDE_DIR=/usr/include/mpc -DMPCDEC_LIBRARY=/usr/lib/libmpcdec.a -DCMAKE_BUILD_TYPE=Release
LSB_SHAREDLIBPATH=/opt/lsb/local/lib/ make
PKG_CONFIG_PATH=/opt/lsb/lib/pkgconfig:/usr/lib/pkgconfig cmake .. -DFLAT_INSTALL=ON -DCMAKE_TOOLCHAIN_FILE=../cmake/lsb-4-0.cmake -DCMAKE_C_FLAGS="--lsb-besteffort" -DCMAKE_CXX_FLAGS="--lsb-besteffort" -DMPCDEC_INCLUDE_DIR=/usr/include/mpc -DMPCDEC_LIBRARY=/usr/lib/libmpcdec.a -DCMAKE_BUILD_TYPE=Release -DFFMPEG_VERSION=0.6.2 -DFFMPEG_NEW_INC_DIR=/opt/lsb/local/ffmpeg/dest/usr/include/ -DFFMPEG_NEW_LIB_DIR=/opt/lsb/local/ffmpeg/dest/usr/lib/
LSB_SHAREDLIBPATH=/opt/lsb/local/ffmpeg/dest/usr/lib/:/opt/lsb/local/lib/ make
find . -executable -type f -exec chrpath -d {} \;
make package

cd ../build32-sse2

PKG_CONFIG_PATH=/opt/lsb/lib/pkgconfig:/usr/lib/pkgconfig cmake .. -DFLAT_INSTALL=ON -DCMAKE_TOOLCHAIN_FILE=../cmake/lsb-4-0.cmake -DCMAKE_C_FLAGS="--lsb-besteffort" -DCMAKE_CXX_FLAGS="--lsb-besteffort" -DMPCDEC_INCLUDE_DIR=/usr/include/mpc -DMPCDEC_LIBRARY=/usr/lib/libmpcdec.a -DCMAKE_BUILD_TYPE=Release -DUSE_SSE2=ON
LSB_SHAREDLIBPATH=/opt/lsb/local/lib/ make
PKG_CONFIG_PATH=/opt/lsb/lib/pkgconfig:/usr/lib/pkgconfig cmake .. -DFLAT_INSTALL=ON -DCMAKE_TOOLCHAIN_FILE=../cmake/lsb-4-0.cmake -DCMAKE_C_FLAGS="--lsb-besteffort" -DCMAKE_CXX_FLAGS="--lsb-besteffort" -DMPCDEC_INCLUDE_DIR=/usr/include/mpc -DMPCDEC_LIBRARY=/usr/lib/libmpcdec.a -DCMAKE_BUILD_TYPE=Release -DUSE_SSE2=ON -DFFMPEG_VERSION=0.6.2 -DFFMPEG_NEW_INC_DIR=/opt/lsb/local/ffmpeg/dest/usr/include/ -DFFMPEG_NEW_LIB_DIR=/opt/lsb/local/ffmpeg/dest/usr/lib/
LSB_SHAREDLIBPATH=/opt/lsb/local/ffmpeg/dest/usr/lib/:/opt/lsb/local/lib/ make
find . -executable -type f -exec chrpath -d {} \;
make package

cd ..
