#!/bin/bash
set -e

cd mingw64
cmake .. -DFLAT_INSTALL=ON -DCMAKE_TOOLCHAIN_FILE=../cmake/x86_64-w64-mingw32.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/local/bin;/local"
make package
cd ../mingw
cmake .. -DFLAT_INSTALL=ON -DCMAKE_TOOLCHAIN_FILE=../cmake/i686-w64-mingw32.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/local/bin;/local"
make package
cd ../mingw-sse2
cmake .. -DFLAT_INSTALL=ON -DCMAKE_TOOLCHAIN_FILE=../cmake/i686-w64-mingw32.cmake -DCMAKE_BUILD_TYPE=Release -DUSE_SSE2=ON -DCMAKE_PREFIX_PATH="/local/bin;/local"
make package
cd ..
