#!/bin/bash
set -e

rm -r build/*        || true
rm -r build32/*      || true
rm -r build32-sse2/* || true
rm -r mingw/*        || true
rm -r mingw-sse2/*   || true
rm -r mingw64/*      || true

schroot -c lsb doc/build-lsb-64
schroot -c lsb-32 doc/build-lsb-32
schroot -c mingw-w64 doc/build-mingw

cp build/libebur128-*-Linux64.tar.gz .
cp build/libebur128-*-Source.tar.gz .
cp build/libebur128-*-Source.zip .
cp build32/libebur128-*-Linux.tar.gz .
cp build32-sse2/libebur128-*-Linux-sse2.tar.gz .
cp mingw/libebur128-*-win32.zip .
cp mingw-sse2/libebur128-*-win32-sse2.zip .
cp mingw64/libebur128-*-win64.zip .
