#!/bin/bash
# setup a schroot for LSB compiling
set -e

cd
apt-get -y update
apt-get -y upgrade
apt-get -y install lsb

mkdir lsb
cd lsb/
wget http://ftp.linux-foundation.org/pub/lsb/bundles/released-4.1.0/sdk/lsb-sdk-4.1.0-4.x86_64.tar.gz
tar xf lsb-sdk-4.1.0-4.x86_64.tar.gz
cd lsb-sdk/
yes | ./install.sh
cd ../..

apt-get -y install cmake-curses-gui libsndfile-dev libmpg123-dev libmpcdec-dev libtag1-dev libavformat-dev chrpath

mkdir /opt/lsb/local
mkdir /opt/lsb/local/lib64
cd /opt/lsb/local/lib64
ln -s /usr/lib/libtag.so .
ln -s /usr/lib/libavformat.so .
ln -s /usr/lib/libavcodec.so .
ln -s /usr/lib/libsndfile.so .
ln -s /usr/lib/libmpg123.so .
ln -s /usr/lib/libmpcdec.so .
cd /opt/lsb/local
mkdir ffmpeg
cd ffmpeg
wget http://cdn.debian.net/debian/pool/main/liba/libav/libavcodec-dev_0.6.2-1_amd64.deb
wget http://cdn.debian.net/debian/pool/main/liba/libav/libavcodec52_0.6.2-1_amd64.deb
wget http://cdn.debian.net/debian/pool/main/liba/libav/libavformat-dev_0.6.2-1_amd64.deb
wget http://cdn.debian.net/debian/pool/main/liba/libav/libavformat52_0.6.2-1_amd64.deb
wget http://cdn.debian.net/debian/pool/main/liba/libav/libavutil50_0.6.2-1_amd64.deb
wget http://cdn.debian.net/debian/pool/main/liba/libav/libavutil-dev_0.6.2-1_amd64.deb
mkdir dest
find *.deb -exec dpkg-deb -x {} dest \;

# as user
# PKG_CONFIG_PATH=/opt/lsb/lib64/pkgconfig:/usr/lib/pkgconfig cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/lsb-4-0.cmake -DCMAKE_C_FLAGS="--lsb-besteffort" -DCMAKE_CXX_FLAGS="--lsb-besteffort" -DMPCDEC_INCLUDE_DIR=/usr/include/mpc -DMPCDEC_LIBRARY=/usr/lib/libmpcdec.a -DCMAKE_BUILD_TYPE=Release
# LSB_SHAREDLIBPATH=/opt/lsb/local/lib64/ make
# PKG_CONFIG_PATH=/opt/lsb/lib64/pkgconfig:/usr/lib/pkgconfig cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/lsb-4-0.cmake -DCMAKE_C_FLAGS="--lsb-besteffort" -DCMAKE_CXX_FLAGS="--lsb-besteffort" -DMPCDEC_INCLUDE_DIR=/usr/include/mpc -DMPCDEC_LIBRARY=/usr/lib/libmpcdec.a -DCMAKE_BUILD_TYPE=Release -DFFMPEG_VERSION=0.6.1 -DFFMPEG_NEW_INC_DIR=/opt/lsb/local/ffmpeg/dest/usr/include/ -DFFMPEG_NEW_LIB_DIR=/opt/lsb/local/ffmpeg/dest/usr/lib/
# LSB_SHAREDLIBPATH=/opt/lsb/local/ffmpeg/dest/usr/lib/:/opt/lsb/local/lib64/ make
# find . -executable -type f -exec chrpath -d {} \;
# make package
