#!/bin/bash
# setup a schroot for Mingw-w64 compiling
set -e

cd
apt-get -y update
apt-get -y upgrade
apt-get -y install bzip2

mkdir mingw
cd mingw

wget http://mingw-w64-dgn.googlecode.com/files/mingw-w32-i686-cross-i686-bin-20110220.tar.bz2
wget http://mingw-w64-dgn.googlecode.com/files/mingw-w64-x86_64-cross-i686-bin-20110220.tar.bz2
tar xf mingw-w32-i686-cross-i686-bin-20110220.tar.bz2
rm -r cross/{include,mingw,share}
mv cross/bin/*.dll cross/i686-w64-mingw32/bin/
tar xf mingw-w64-x86_64-cross-i686-bin-20110220.tar.bz2
rm -r cross/{include,mingw,share}
mv cross/bin/*.dll cross/x86_64-w64-mingw32/bin/
cp -r cross/* /usr/
cd ..

apt-get -y install cmake-curses-gui build-essential libc6-i386 lib32z1

mkdir libs
cd libs
echo "set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_C_COMPILER i686-w64-mingw32-gcc)
set(CMAKE_CXX_COMPILER i686-w64-mingw32-g++)
set(CMAKE_FIND_ROOT_PATH  /usr/i686-w64-mingw32)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)" > i686-w64-mingw32.cmake
echo "set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)
set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)
set(CMAKE_FIND_ROOT_PATH  /usr/x86_64-w64-mingw32)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)" > x86_64-w64-mingw32.cmake

wget --no-check-certificate https://github.com/taglib/taglib/tarball/stable
tar xf stable
cd taglib-taglib-*
mkdir build
cd build
cmake .. -DCMAKE_TOOLCHAIN_FILE=../../i686-w64-mingw32.cmake -DCMAKE_BUILD_TYPE=Release
mkdir dest
make DESTDIR=`pwd`/dest install
cd dest/usr
cp -r local/ /usr/i686-w64-mingw32/
cd ../..
rm -r *
cmake .. -DCMAKE_TOOLCHAIN_FILE=../../x86_64-w64-mingw32.cmake -DCMAKE_BUILD_TYPE=Release
mkdir dest
make DESTDIR=`pwd`/dest install
cd dest/usr
cp -r local/ /usr/x86_64-w64-mingw32/
cd ../../../../

apt-get -y install dtrx
wget http://ftp.gnome.org/pub/gnome/binaries/win32/glib/2.26/glib_2.26.1-1_win32.zip
wget http://ftp.gnome.org/pub/gnome/binaries/win32/glib/2.26/glib-dev_2.26.1-1_win32.zip
wget http://ftp.gnome.org/pub/gnome/binaries/win32/dependencies/gettext-runtime_0.18.1.1-2_win32.zip
dtrx glib-dev_2.26.1-1_win32.zip
dtrx glib_2.26.1-1_win32.zip
dtrx gettext-runtime_0.18.1.1-2_win32.zip
cp -r glib-dev_2.26.1-1_win32/* /usr/i686-w64-mingw32/local/
cp -r glib_2.26.1-1_win32/* /usr/i686-w64-mingw32/local/
cp -r gettext-runtime_0.18.1.1-2_win32/* /usr/i686-w64-mingw32/local/

wget http://ftp.gnome.org/pub/gnome/binaries/win64/glib/2.26/glib_2.26.1-1_win64.zip
wget http://ftp.gnome.org/pub/gnome/binaries/win64/glib/2.26/glib-dev_2.26.1-1_win64.zip
wget http://ftp.gnome.org/pub/gnome/binaries/win64/dependencies/gettext-runtime_0.18.1.1-2_win64.zip
dtrx glib_2.26.1-1_win64.zip
dtrx glib-dev_2.26.1-1_win64.zip
dtrx gettext-runtime_0.18.1.1-2_win64.zip
cp -r glib-dev_2.26.1-1_win64/* /usr/x86_64-w64-mingw32/local/
cp -r glib_2.26.1-1_win64/* /usr/x86_64-w64-mingw32/local/
cp -r gettext-runtime_0.18.1.1-2_win64/* /usr/x86_64-w64-mingw32/local/

apt-get -y install wine unrar
wget http://sourceforge.net/projects/innounp/files/innounp/innounp%200.35/innounp035.rar
wget http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.23-w32-setup.exe
wget http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.23-w64-setup.exe
unrar x innounp035.rar
wine innounp -x libsndfile-1.0.23-w32-setup.exe
cp \{app\}/libsndfile-1.dll /usr/i686-w64-mingw32/local/bin/
cp \{app\}/include/sndfile.h* /usr/i686-w64-mingw32/local/include/
rm -r \{app\}
rm install_script.iss
wine innounp -x libsndfile-1.0.23-w64-setup.exe
cp \{app\}/libsndfile-1.dll /usr/x86_64-w64-mingw32/local/bin/
cp \{app\}/include/sndfile.h* /usr/x86_64-w64-mingw32/local/include/
rm -r \{app\}
rm install_script.iss

wget http://www.mpg123.de/download/win64/mpg123-1.13.1-x86-64.zip
wget http://www.mpg123.de/download/win32/mpg123-1.13.1-x86.zip
dtrx mpg123-1.13.1-x86.zip
dtrx mpg123-1.13.1-x86-64.zip
cp mpg123-1.13.1-x86/mpg123.h /usr/i686-w64-mingw32/local/include/
cp mpg123-1.13.1-x86/libmpg123-0.dll /usr/i686-w64-mingw32/local/bin/
cp mpg123-1.13.1-x86-64/mpg123.h /usr/x86_64-w64-mingw32/local/include/
cp mpg123-1.13.1-x86-64/libmpg123-0.dll /usr/x86_64-w64-mingw32/local/bin/

apt-get source libmpc
cd libmpc-0.1~r459
sed -i -e '/add_subdirectory(mpcgain)/d' -e '/add_subdirectory(mpcchap)/d' CMakeLists.txt
mkdir build
cd build
cmake .. -DCMAKE_TOOLCHAIN_FILE=../../i686-w64-mingw32.cmake
make
cp libmpcdec/libmpcdec_static.a /usr/i686-w64-mingw32/local/lib/
cp -r ../include/mpc/ /usr/i686-w64-mingw32/local/include/
rm -r *
cmake .. -DCMAKE_TOOLCHAIN_FILE=../../x86_64-w64-mingw32.cmake
make
cp libmpcdec/libmpcdec_static.a /usr/x86_64-w64-mingw32/local/lib/
cp -r ../include/mpc/ /usr/x86_64-w64-mingw32/local/include/
cd ../../

wget http://www.ffmpeg.org/releases/ffmpeg-0.6.2.tar.bz2
tar xf ffmpeg-0.6.2.tar.bz2
cd ffmpeg-0.6.2
mkdir dest
./configure --enable-memalign-hack --target-os=mingw32 --arch=x86_64 \
            --sysroot=/usr/x86_64-w64-mingw32 \
            --cross-prefix=x86_64-w64-mingw32- --enable-shared --disable-swscale --disable-dxva2
make DESTDIR=`pwd`/dest install
cp -r dest/usr/local/* /usr/x86_64-w64-mingw32/local/
cd ..
rm -r ffmpeg-0.6.2
tar xf ffmpeg-0.6.2.tar.bz2
cd ffmpeg-0.6.2
mkdir dest
sed -i -e '2230,2236d' configure
./configure --enable-memalign-hack --target-os=mingw32 --arch=x86 \
            --sysroot=/usr/i686-w64-mingw32 \
            --cross-prefix=i686-w64-mingw32- --enable-shared --disable-swscale --disable-dxva2
make DESTDIR=`pwd`/dest install
cp -r dest/usr/local/* /usr/i686-w64-mingw32/local/
cd ..

x86_64-w64-mingw32-strip /usr/x86_64-w64-mingw32/local/bin/*.dll
i686-w64-mingw32-strip /usr/i686-w64-mingw32/local/bin/*.dll

# as user
# cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/x86_64-w64-mingw32.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/local/bin;/local"
# make package
# cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/i686-w64-mingw32.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/local/bin;/local"
# make package
