include(LibFindMacros)
libfind_package(GSTREAMER LibXml2)
libfind_pkg_check_modules(GSTREAMER_PKGCONF gstreamer-0.10)

foreach(arg ${GSTREAMER_PKGCONF_CFLAGS})
    if (NOT "${arg}" MATCHES "-I.*")
        set(GSTREAMER_CFLAGS "${GSTREAMER_CFLAGS} ${arg}")
    endif()
endforeach()

find_path(GSTREAMER_INCLUDE_DIR
    NAMES gst/gst.h
    PATHS ${GSTREAMER_PKGCONF_INCLUDE_DIRS}
    PATH_SUFFIXES gstreamer-0.10
)

find_library(GSTREAMER_LIBRARY
    NAMES gstreamer-0.10
    PATHS ${GSTREAMER_PKGCONF_LIBRARY_DIRS}
)

find_library(GSTAPP_LIBRARY
    NAMES gstapp-0.10
    PATHS ${GSTREAMER_PKGCONF_LIBRARY_DIRS}
)

find_library(GSTBASE_LIBRARY
    NAMES gstbase-0.10
    PATHS ${GSTREAMER_PKGCONF_LIBRARY_DIRS}
)

find_library(GSTAUDIO_LIBRARY
    NAMES gstaudio-0.10
    PATHS ${GSTREAMER_PKGCONF_LIBRARY_DIRS}
)

set(GSTREAMER_PROCESS_INCLUDES GSTREAMER_INCLUDE_DIR LIBXML2_INCLUDE_DIR)
set(GSTREAMER_PROCESS_LIBS GSTREAMER_LIBRARY GSTAPP_LIBRARY GSTBASE_LIBRARY GSTAUDIO_LIBRARY LIBXML2_LIBRARIES)
libfind_process(GSTREAMER)
