macro(to_yes_no vars)
  foreach(var ${ARGV})
    if(${var})
      set(${var} "yes")
    else()
      set(${var} "no ")
    endif()
  endforeach()
endmacro()

macro(if_empty_print_missing vars)
  foreach(var ${ARGV})
    if(NOT ${var})
      set(${var} "<not set>")
    endif()
  endforeach()
endmacro()

function(to_space_list sc_list)
    set(ret)
    foreach(val ${${sc_list}})
        set(ret "${ret} ${val}")
    endforeach()
    if(ret)
        string(STRIP ${ret} ret)
        set(${sc_list} "${ret}" PARENT_SCOPE)
    endif()
endfunction()
